{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import os\n",
    "for dirname, _, filenames in os.walk('/kaggle/input'):\n",
    "    for filename in filenames:\n",
    "        print(os.path.join(dirname, filename))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "dlopen(/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/_C.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib\n  Referenced from: <5F8A9E3F-45D0-33ED-BCD9-81452ED3FD7D> /Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/libtorch_cpu.dylib\n  Reason: tried: '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/../../../../liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/../../../liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/../../../liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/bin/../lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[12], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mfastai\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mvision\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mall\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n",
      "File \u001b[0;32m~/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/fastai/vision/all.py:1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m models\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mbasics\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mcallback\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mall\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n",
      "File \u001b[0;32m~/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/fastai/vision/models/__init__.py:1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m xresnet\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m unet\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtvm\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n",
      "File \u001b[0;32m~/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/fastai/vision/models/xresnet.py:5\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;66;03m# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/11_vision.models.xresnet.ipynb.\u001b[39;00m\n\u001b[1;32m      2\u001b[0m \n\u001b[1;32m      3\u001b[0m \u001b[38;5;66;03m# %% ../../../nbs/11_vision.models.xresnet.ipynb 2\u001b[39;00m\n\u001b[1;32m      4\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m__future__\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m annotations\n\u001b[0;32m----> 5\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mtorch_basics\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m\n\u001b[1;32m      6\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m: \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtorchvision\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mmodels\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mutils\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m load_state_dict_from_url\n\u001b[1;32m      7\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mModuleNotFoundError\u001b[39;00m: \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtorch\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mhub\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m load_state_dict_from_url\n",
      "File \u001b[0;32m~/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/fastai/torch_basics.py:1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtorch\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m multiprocessing\n\u001b[1;32m      2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;21;01mplatform\u001b[39;00m\u001b[38;5;241m,\u001b[39m\u001b[38;5;21;01mos\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m platform\u001b[38;5;241m.\u001b[39msystem()\u001b[38;5;241m==\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mDarwin\u001b[39m\u001b[38;5;124m'\u001b[39m:\n\u001b[1;32m      4\u001b[0m     \u001b[38;5;66;03m# Python 3.8 changed to 'spawn' but that doesn't work with PyTorch DataLoader w n_workers>0\u001b[39;00m\n",
      "File \u001b[0;32m~/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/__init__.py:239\u001b[0m\n\u001b[1;32m    237\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m USE_GLOBAL_DEPS:\n\u001b[1;32m    238\u001b[0m         _load_global_deps()\n\u001b[0;32m--> 239\u001b[0m     \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mtorch\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01m_C\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m \u001b[38;5;241m*\u001b[39m  \u001b[38;5;66;03m# noqa: F403\u001b[39;00m\n\u001b[1;32m    241\u001b[0m \u001b[38;5;66;03m# Appease the type checker; ordinarily this binding is inserted by the\u001b[39;00m\n\u001b[1;32m    242\u001b[0m \u001b[38;5;66;03m# torch._C module initialization code in C\u001b[39;00m\n\u001b[1;32m    243\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m TYPE_CHECKING:\n",
      "\u001b[0;31mImportError\u001b[0m: dlopen(/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/_C.cpython-312-darwin.so, 0x0002): Library not loaded: @rpath/liblapack.3.dylib\n  Referenced from: <5F8A9E3F-45D0-33ED-BCD9-81452ED3FD7D> /Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/libtorch_cpu.dylib\n  Reason: tried: '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/../../../../liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/../../../liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/lib/python3.12/site-packages/torch/../../../liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/bin/../lib/liblapack.3.dylib' (no such file), '/Users/lilyjeong/Documents/Python_workspace/fastai_PyTorch/.conda/bin/../lib/liblapack.3.dylib' (no such file), '/usr/local/lib/liblapack.3.dylib' (no such file), '/usr/lib/liblapack.3.dylib' (no such file, not in dyld cache)"
     ]
    }
   ],
   "source": [
    "from fastai.vision.all import *\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
